name: Automated Tests

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          test: npm run cypress:open

  react-testing-library-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run React Testing Library Tests
        uses: setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test:coverage
